{
  "name"                 :  "TDS Management",
  "summary"              :  """TDS Management""",
  "category"             :  "Accounting",
  "version"              :  "1.1.1",
  "sequence"             :  1,
  "depends"              :  ['account', 'contacts'],
  "data"                 :  [
                             'security/ir.model.access.csv',
                             'security/security.xml',
                             'views/res_config_settings_view.xml',
                             'views/account_move_view.xml',
                             'views/tds_management.xml',
                             'views/res_partner_inherit.xml',
                            ],
  "demo"                 :  ['data/discount_demo.xml'],
  "application"          :  True,
  "installable"          :  True,
  "auto_install"         :  False,
  "pre_init_hook"        :  "pre_init_check",
}